# Create NumPy Array

In [37]:
import numpy as np

In [38]:
nums=[1,2,3]

In [39]:
nums=np.array(nums)

In [40]:
nums

array([1, 2, 3])

In [41]:
nums2=[[1,2,3],[4,5,6]]

In [42]:
nums2=np.array(nums2)

In [43]:
nums2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
nums3=[[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]]

In [45]:
nums3=np.array(nums3)

In [46]:
nums3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [47]:
nums.ndim

1

In [48]:
nums2.ndim

2

In [49]:
nums3.ndim

3

In [50]:
nums.shape

(3,)

In [51]:
nums2.shape

(2, 3)

In [52]:
nums3.shape

(2, 2, 3)

Note-All Values of numpy array have always similer data type

In [53]:
nums.dtype

dtype('int32')

In [54]:
nums=[1,2.0,3]

In [55]:
nums=np.array(nums)

In [56]:
nums.dtype

dtype('float64')

In [57]:
nums

array([1., 2., 3.])

In [58]:
nums=[1,2,"3"]

In [59]:
nums=np.array(nums)

In [60]:
nums

array(['1', '2', '3'], dtype='<U11')

In [61]:
nums.dtype

dtype('<U11')

In [63]:
nums=[1,2,'s',False]

In [64]:
nums=np.array(nums)

In [65]:
nums

array(['1', '2', 's', 'False'], dtype='<U11')