In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr*2

array([2, 4, 6, 8])

In [5]:
arr+10

array([11, 12, 13, 14])

In [6]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [7]:
arr2=arr.reshape(2,2)

In [9]:
arr2

array([[1, 2],
       [3, 4]])

In [10]:
arr2/1

array([[1., 2.],
       [3., 4.]])