In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [3]:
arr1+arr2

array([ 6,  8, 10, 12])

In [5]:
arr3=np.array([0,3,4])

In [7]:
arr1+arr3    #Shape Same Na Hone Ki Wajah Se Error Ayega

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [8]:
arr1**arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [9]:
arr1*arr2

array([ 5, 12, 21, 32])

In [10]:
arr1*arr1

array([ 1,  4,  9, 16])

In [11]:
arr3=np.array([0,9,8,7])

In [12]:
arr1*arr2+arr3

array([ 5, 21, 29, 39])

In [13]:
arr1/arr2*arr1+arr3

array([0.2       , 9.66666667, 9.28571429, 9.        ])

In [19]:
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,3)
matrix2=np.random.randint(5,15,9).reshape(3,3)

In [20]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [21]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [22]:
matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [23]:
matrix1*matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [24]:
# for matrix multiplication

In [ ]:
matrix1.do