In [1]:
import numpy as np

In [2]:
arr=np.array([15,16,66,4,46])

In [5]:
# min- to get minimum element of numpy array

In [3]:
np.min(arr)

4

In [6]:
# max- to get maxmum element of numpy array

In [4]:
np.max(arr)

66

In [7]:
# argmin- to get index of minimum element in numpy array

In [8]:
np.argmin(arr)

3

In [9]:
# argmax- to get index of maxmum element in numpy array

In [10]:
np.argmax(arr)

2

In [12]:
# sqrt- to get square root of every element in numpy array

In [11]:
np.sqrt(arr)

array([3.87298335, 4.        , 8.1240384 , 2.        , 6.78232998])

In [13]:
arr

array([15, 16, 66,  4, 46])

In [16]:
# exp- to get euler's number power of every element

In [17]:
np.exp(arr)

array([3.26901737e+06, 8.88611052e+06, 4.60718663e+28, 5.45981500e+01,
       9.49611942e+19])

In [19]:
2.71828**15

3268984.3889371986

In [27]:
# linspace - to get n number of elements with are evenly spaced

In [24]:
np.linspace(0,50,3)

array([ 0., 25., 50.])

In [26]:
np.linspace(1,100,25)

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [28]:
arr4=np.array([14,0,1,5],dtype="bool")

In [29]:
array

NameError: name 'array' is not defined