In [1]:
import numpy as np

In [2]:
np.random.seed(123)
arr=np.random.randint(1,15,15)

In [3]:
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [4]:
# shuffle - to shuffle the elements of numpy array

In [5]:
np.random.shuffle(arr)

In [6]:
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [7]:
# unique- to get array with unique elements

In [8]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [11]:
np.unique(arr).size

10

In [12]:
np.unique(arr,index=True,counts=True)

TypeError: unique() got an unexpected keyword argument 'index'