### Import numpy library  

In [1]:
import numpy as np

### Create an Array using array function  

In [2]:
arr1=np.array([1,2,3,5])

### Create an Array containing numbers from 20 to 40 

In [7]:
arr2=np.arange(20,41)
arr1

array([1, 2, 3, 5])

### Create an array which contain 10 elements and every element is 5  

In [13]:
arr3=np.ones(10)*5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [24]:
arr4=np.random.randint(1,100,27).reshape(3,3,3)

arr4

array([[[ 3, 47, 30],
        [26, 56, 36],
        [48, 94, 69]],

       [[10, 35, 98],
        [98, 50, 56],
        [ 2, 25, 80]],

       [[34, 33, 48],
        [86, 80, 33],
        [46, 58, 83]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [29]:
arr5=np.random.rand(5,5)
arr5

array([[0.09255784, 0.85429713, 0.82244674, 0.0827589 , 0.62384632],
       [0.32034991, 0.62843901, 0.25832863, 0.90995628, 0.7548653 ],
       [0.94989127, 0.21232607, 0.28077053, 0.18724166, 0.65841629],
       [0.79836125, 0.07542216, 0.15565578, 0.23201497, 0.49108429],
       [0.09637019, 0.22409658, 0.40567696, 0.49468261, 0.09483677]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [37]:
arr6=np.random.randint(1,100,20)
arr6[arr6%2==0]=-1
arr6

array([-1, 73, -1, -1,  9, 91, 61, -1, 81, 55, 99, 85, 91, -1, 55, -1,  5,
       -1, 69, -1])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [47]:
matrix=np.array([[5 , 10, 15, 20, 25],
                [30, 35, 40, 45, 50], 
                [55, 60, 65, 70, 75],
                [80, 85, 90, 95, 100]])
matrix[1:3,:3]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [48]:
arr7=np.array([1,2,3])
arr8=np.array([5,6,7])
np.hstack((arr7,arr8))

array([1, 2, 3, 5, 6, 7])

### Stack 2-d matrix horizontally and vertically

In [49]:
matrix1=np.random.randint(1,100,9).reshape(3,3)
matrix2=np.random.randint(1,50,9).reshape(3,3)

In [50]:
matrix1

array([[80, 93, 98],
       [31, 64, 46],
       [37, 16, 95]])

In [51]:
matrix2

array([[11, 25, 40],
       [ 4, 40, 36],
       [41, 35, 44]])