In [9]:
import numpy as np

In [10]:
#zeros-get array with values zero

In [11]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [12]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#ones-get array with values one

In [15]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [16]:
#eye-get Identity matrix

In [17]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
#diag-to get digonal of array

In [21]:
np.diag(arr)

array([1., 1., 1.])

In [22]:
#randint-get the random number parameter (start,end,number of numbers)

In [24]:
rand_arr=np.random.randint(1,15,4)
rand_arr

array([14,  3,  2,  8])

In [25]:
# rand-get random number between 0 and 1 parameter(number of numbers)

In [26]:
rand_arr=np.random.rand(4)
rand_arr

array([0.74386249, 0.48920972, 0.63155126, 0.19716944])

In [28]:
rand_arr=np.random.rand(2,3)
rand_arr

array([[0.1197293 , 0.84757168, 0.31406378],
       [0.29560207, 0.5206689 , 0.34103461]])

In [30]:
# randn- ye random number dega joki zero ke centered honge

In [31]:
rand_arr=np.random.randn(4)
rand_arr

array([-0.06716852,  1.17624333, -2.05296551,  1.33672844])

In [ ]:
# mean-average

In [32]:
np.mean(rand_arr)

0.09820943464441872