# Reshaping Of Data

In [1]:
import numpy as np

In [3]:
arr=np.random.randint(1,100,20)

In [4]:
arr

array([93, 70, 39, 10, 43, 66, 18, 32, 64, 16, 81, 28, 44, 62, 34, 35, 53,
       38, 97, 74])

In [5]:
arr.ndim

1

In [7]:
arr.shape

(20,)

In [8]:
arr=arr.reshape(2,10)

In [9]:
arr

array([[93, 70, 39, 10, 43, 66, 18, 32, 64, 16],
       [81, 28, 44, 62, 34, 35, 53, 38, 97, 74]])

In [10]:
arr.shape

(2, 10)

In [11]:
arr.ndim

2

In [12]:
arr=arr.reshape(20)

In [13]:
arr

array([93, 70, 39, 10, 43, 66, 18, 32, 64, 16, 81, 28, 44, 62, 34, 35, 53,
       38, 97, 74])

In [14]:
arr2=np.random.randint(1,100,50)

In [16]:
arr2

array([22, 55, 84, 64, 27, 79, 75, 21, 26, 52, 52, 16, 38, 42,  5, 87, 58,
       28, 48, 68, 40, 41, 50, 96, 44, 74, 85,  3, 60, 37, 38, 58, 84, 37,
       73, 80,  5, 47, 41, 98, 89, 87, 35,  4, 42, 85, 76, 45, 61, 88])

In [19]:
arr2=arr2.reshape(10,5)

In [20]:
arr2

array([[22, 55, 84, 64, 27],
       [79, 75, 21, 26, 52],
       [52, 16, 38, 42,  5],
       [87, 58, 28, 48, 68],
       [40, 41, 50, 96, 44],
       [74, 85,  3, 60, 37],
       [38, 58, 84, 37, 73],
       [80,  5, 47, 41, 98],
       [89, 87, 35,  4, 42],
       [85, 76, 45, 61, 88]])

In [21]:
arr2=arr2.reshape(2,5,5)

In [22]:
arr2

array([[[22, 55, 84, 64, 27],
        [79, 75, 21, 26, 52],
        [52, 16, 38, 42,  5],
        [87, 58, 28, 48, 68],
        [40, 41, 50, 96, 44]],

       [[74, 85,  3, 60, 37],
        [38, 58, 84, 37, 73],
        [80,  5, 47, 41, 98],
        [89, 87, 35,  4, 42],
        [85, 76, 45, 61, 88]]])