In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,101,10)

In [3]:
arr

array([76, 18, 48, 55, 40, 92, 33, 28,  3, 77])

In [4]:
arr=np.random.randint(1,101,10)

In [5]:
arr

array([59, 98, 88, 58, 72, 51,  7, 43,  3, 65])

In [6]:
# har bar same random number generate karne ke liye seed method use karna hoga wo random number generate karne ke pahle

In [8]:
np.random.seed(12)
arr=np.random.randint(1,101,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [9]:
np.random.seed(12)
arr=np.random.randint(1,101,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [10]:
np.random.seed(123)
arr=np.random.randint(1,101,10)
arr

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])