In [1]:
import numpy as np

In [2]:
arr=np.array([i for i in range(5,26,5)])

In [3]:
arr

array([ 5, 10, 15, 20, 25])

In [4]:
arr[0]

5

In [5]:
arr[1]

10

In [6]:
arr[4]

25

In [7]:
arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [8]:
arr[-1]

25

In [9]:
arr[-4]

10

In [10]:
arr[:]

array([ 5, 10, 15, 20, 25])

In [11]:
arr[:2]

array([ 5, 10])

In [12]:
arr[2:]

array([15, 20, 25])

In [13]:
arr[0:3]

array([ 5, 10, 15])

In [14]:
arr[2:4:2]

array([15])