# 1.Create 2D Array

In [1]:
import numpy as np

In [10]:
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [11]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# 2.Indexing Using Double Bracket Notation

In [12]:
matrix[0][0]

5

In [15]:
matrix[1][1]

25

# 3.Indexing Using Single Braket Notation(Recomended)

In [16]:
matrix[0,1]

10

In [17]:
matrix[1,1]

25

In [18]:
matrix[2,2]

45

In [20]:
matrix[-1,-2]

40

# 4.Slicing Using Single Bracket Notation

In [21]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
#[[5,10],
#[20,25]]

In [25]:
# array[row start:row end,col start,col end]

In [26]:
matrix[:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [27]:
matrix[:-1,:-1]

array([[ 5, 10],
       [20, 25]])

In [28]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [31]:
np.random.seed(123)
matrix2=np.random.randint(1,101,25).reshape(5,-1)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [32]:
# 87, 98, 97
# 33, 47, 97
# 79, 37, 97

In [34]:
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [35]:
matrix2[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])