In [1]:
import numpy as np

In [2]:
arr=np.array([i for i in range(5,31,5)])

In [3]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [4]:
scliced_arr=arr[2:5]

In [5]:
scliced_arr

array([15, 20, 25])

In [6]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [7]:
arr[:2]=0

In [8]:
arr

array([ 0,  0, 15, 20, 25, 30])

In [9]:
scliced_arr[:]=0

In [11]:
scliced_arr

array([0, 0, 0])

In [12]:
arr

array([ 0,  0,  0,  0,  0, 30])

In [13]:
# scliced_arr ke values ko zero karne se arr ke bhi value me change ho gaya kyoki scliced_arr arr ka view hai copy nhi

In [14]:
arr=np.array([i for i in range(5,31,5)])

In [15]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [16]:
scliced_arr=arr[2:5].copy()

In [17]:
scliced_arr

array([15, 20, 25])

In [18]:
scliced_arr[:]=0

In [19]:
scliced_arr

array([0, 0, 0])

In [20]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [21]:
# scliced_arr ke values ko zero karne se arr ke bhi value me change nhi huaa kyoki scliced_arr arr ka copy hai