In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
mask=arr>5

In [7]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [8]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [10]:
arr[arr==5]

array([5])